import pyautogui as pyag
import time as t

pyag.press ("win")
t.sleep (1)
pyag.write ("chrome")
t.sleep (1)
pyag.press ("enter")
t.sleep (1)
pyag.hotkey('ctrl', 'l')
t.sleep(1)
pyag.write("https://www.youtube.com.br")
t.sleep(1)
pyag.press ("enter")
t.sleep(10)
pyag.click(706, 108)
t.sleep(1)
pyag.write("revampt")
t.sleep(1)
pyag.press ("enter")
t.sleep(10)
pyag.click(534, 306)
t.sleep(1)
pyag.press ("enter")
t.sleep(10)
pyag.click(371, 738)